name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        dotNetInstallVersion: [3.1.302]
        dotNetRunVersion: [netcoreapp3.1]
        solution: [Microsoft.Identity.Web.sln]
        include:
          - DotNetInstallVersion: 5.0.100
            DotNetRunVersion: net5.0
            Solution: Microsoft.Identity.Web.sln

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Setup .NET ${{ matrix.dotNetInstallVersion }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotNetInstallVersion }}

    - name: Build with .NET ${{ matrix.dotNetRunVersion }}
      run: dotnet test -f ${{ matrix.dotNetRunVersion }} -p:FROM_GITHUB_ACTION=true --configuration Release ${{ matrix.solution }}
